<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Cycling_img-responsive</name>
   <tag></tag>
   <elementGuidId>21747dfb-81d1-47d2-b38b-2c90621dc7fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#2008775850 > div.activity-card > img.img-responsive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='2008775850']/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Cycling North Venwar ₹3174 Duration 4 Hours&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>52abd43a-b1d9-4ea1-a7cf-c0cebc664dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>5e40adce-296c-421b-9ce0-bdcdc78a4164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.pexels.com/photos/1192632/pexels-photo-1192632.jpeg?auto=compress&amp;cs=tinysrgb&amp;h=650&amp;w=940</value>
      <webElementGuid>51b951e7-c106-4e33-aabb-eadf894a1cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2008775850&quot;)/div[@class=&quot;activity-card&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>5cbb1d5c-b9e1-4870-b2eb-953adbd53eed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='2008775850']/div[2]/img</value>
      <webElementGuid>c4ef55ea-32a5-4718-a9ad-e4dcac764037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://images.pexels.com/photos/1192632/pexels-photo-1192632.jpeg?auto=compress&amp;cs=tinysrgb&amp;h=650&amp;w=940')]</value>
      <webElementGuid>535fd75e-9ca0-430b-8181-3b301527694f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div[2]/img</value>
      <webElementGuid>44fba2f8-a7fb-4b4b-97c8-60d272380252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.pexels.com/photos/1192632/pexels-photo-1192632.jpeg?auto=compress&amp;cs=tinysrgb&amp;h=650&amp;w=940']</value>
      <webElementGuid>b6dc9813-a38b-4734-9595-6269ab6fe7c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
