<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_12896b739d036047</name>
   <tag></tag>
   <elementGuidId>5a7075ef-d2bc-4db3-9c17-d5beee148cb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reservation-table > tr > th</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='reservation-table']/tr/th</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//tbody[@id='reservation-table']/tr/th</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=rowheader[name=&quot;12896b739d036047&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>20542e31-e89e-44c6-bedb-26e512db5c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>51469ab5-89a9-43b9-8816-cd5566d1a6cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12896b739d036047</value>
      <webElementGuid>16a30164-9eb2-4c34-b999-866096c785ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody[@id='reservation-table']/tr/th</value>
      <webElementGuid>cc89f505-80c7-4757-b6e7-9ca8aaef97c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='reservation-table']/tr/th</value>
      <webElementGuid>38df2469-3e08-4f56-82b2-cb2b459551d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::th[1]</value>
      <webElementGuid>76bd8546-13d4-4ede-9583-1269fe90e9b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::th[2]</value>
      <webElementGuid>cdb2b9ba-708d-474d-add8-46c796193240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ravisankar N'])[1]/preceding::th[1]</value>
      <webElementGuid>c6a5ca68-8dff-49f5-a48a-62e649a8707e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='North Venwar'])[1]/preceding::th[1]</value>
      <webElementGuid>d8b87b70-f5f5-4c7e-921f-75e7091bbe05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12896b739d036047']/parent::*</value>
      <webElementGuid>46644b9d-4333-4804-8ec2-f9c8af8ddab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/th</value>
      <webElementGuid>50602fae-e6cb-48d1-94c8-7d5a38ca0cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = '12896b739d036047' or . = '12896b739d036047')]</value>
      <webElementGuid>3acaf18e-bbbf-4f4d-9578-38aaf84950f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
