<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_General Comment</name>
   <tag></tag>
   <elementGuidId>06afd235-93a7-4568-9b6a-2092eaf058aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/form/div/div[2]/div[3]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.oxd-text.oxd-text--p.orangehrm-evaluation-grid-general-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;General Comment&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6051483f-1c09-4d2b-a0b7-621a00d03322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-text oxd-text--p orangehrm-evaluation-grid-general-label</value>
      <webElementGuid>06a98202-385a-417d-83df-cec21ed9e5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General Comment</value>
      <webElementGuid>88a1f320-19dc-4978-a837-f24ee9062d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/form[@class=&quot;oxd-form&quot;]/div[1]/div[@class=&quot;orangehrm-evaluation orangehrm-card-container&quot;]/div[@class=&quot;oxd-grid-3 orangehrm-evaluation-grid&quot;]/div[@class=&quot;oxd-grid-item oxd-grid-item--gutters orangehrm-evaluation-grid-general&quot;]/p[@class=&quot;oxd-text oxd-text--p orangehrm-evaluation-grid-general-label&quot;]</value>
      <webElementGuid>7d6b725a-bfe0-4ba1-bd5f-451d30a01839</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/form/div/div[2]/div[3]/div/p</value>
      <webElementGuid>51160c7b-26f0-4354-9bdc-7c075c1d8a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='General Comment']/parent::*</value>
      <webElementGuid>f5284f33-1e68-4007-9083-fe2c9b8e315e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p</value>
      <webElementGuid>bc131c49-570a-4b98-a793-811d5ca4a682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'General Comment' or . = 'General Comment')]</value>
      <webElementGuid>c684fcd1-3d5b-4998-b16f-6101a6fc56fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
