<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>2nd Test suite data driven execution</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>10ae20cc-a0a7-4145-8b09-a7a8f2e97ae2</testSuiteGuid>
   <testCaseLink>
      <guid>34095c83-5b78-4b15-938a-36881c64fd12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/17 New Test case creation/4th Test case</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ee5b20f8-4b67-4263-9405-a92a66c02be5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/17 New Test case creation/5th Test case</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>28a79c8b-b04e-4f52-a77a-7662160e8e1a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test data run/5th Test data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>28a79c8b-b04e-4f52-a77a-7662160e8e1a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>User_name</value>
         <variableId>9a1e6e29-887d-4fd9-bebd-daf09e3af2cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>28a79c8b-b04e-4f52-a77a-7662160e8e1a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Employee_Hints</value>
         <variableId>c19e00ae-695c-4a54-9eb0-d42d6e8b6df3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>acee5aa5-ea3f-4693-bdc5-da48903f3195</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/17 New Test case creation/6th Test case</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d0fedc8b-76b1-426b-8a75-5d87c5051473</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test data run/6th Test case</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d0fedc8b-76b1-426b-8a75-5d87c5051473</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ref_Text</value>
         <variableId>93a2ef4e-1839-4863-8bed-a3ef60271937</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d0fedc8b-76b1-426b-8a75-5d87c5051473</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emp_name</value>
         <variableId>c523b11b-ed1f-4891-a27a-8b6bca84afa1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d0fedc8b-76b1-426b-8a75-5d87c5051473</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>remark</value>
         <variableId>2ea45db1-fa25-4552-8558-a32ba240102f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
