<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>4th test suite data driven execution</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>214eeb2c-e9f6-4c29-9400-899bd171a704</testSuiteGuid>
   <testCaseLink>
      <guid>41017165-34bc-47bc-b1f2-39ec90dac70e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/17 New Test case creation/10th test case</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9ca4c2be-cf9b-4cfb-9fe7-3cbe5db3141e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test data run/10th Test data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>9ca4c2be-cf9b-4cfb-9fe7-3cbe5db3141e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>ee8c7ade-6a3c-4e51-9922-20bb69644665</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9ca4c2be-cf9b-4cfb-9fe7-3cbe5db3141e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>b7bfa503-1e77-479e-a151-91a2249ae0af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9ca4c2be-cf9b-4cfb-9fe7-3cbe5db3141e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>company</value>
         <variableId>eb0ef51d-19c2-446a-bbb9-5e7097d3fad4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9ca4c2be-cf9b-4cfb-9fe7-3cbe5db3141e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>mobile</value>
         <variableId>c391675e-9dbc-4022-994e-497abc8e02c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb57bc43-ddb8-4d88-b072-603c125871f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/17 New Test case creation/11th Test case</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>febe2132-34f6-498a-95f0-0a4a4fe3b8d3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test data run/11 test data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>febe2132-34f6-498a-95f0-0a4a4fe3b8d3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>f319c047-ef86-4c19-b6c3-2e5c08cecced</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>febe2132-34f6-498a-95f0-0a4a4fe3b8d3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>6a90c4a2-538f-4097-89a4-dcb7055ff3b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>febe2132-34f6-498a-95f0-0a4a4fe3b8d3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>e3e9f94f-6c2f-4807-80fc-ac41d8739c02</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>035ef48c-d528-4adb-9c7b-118ee76091b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/17 New Test case creation/12th Test case</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>157b90aa-c1d2-4aa9-a566-2b10fdfe6e0d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Test data run/12 Test data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>157b90aa-c1d2-4aa9-a566-2b10fdfe6e0d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>cardno</value>
         <variableId>e6d75bb6-5609-47f9-871a-0d780e34effa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>157b90aa-c1d2-4aa9-a566-2b10fdfe6e0d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>cvv</value>
         <variableId>4ed5b626-b4f9-450e-9677-cdd7fd9d9a59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>157b90aa-c1d2-4aa9-a566-2b10fdfe6e0d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name</value>
         <variableId>5425100c-ce94-4cfa-870d-2b6e47708eb8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
