<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-6</name>
   <tag></tag>
   <elementGuidId>df8bd06a-2e1c-4065-891f-397c0ca62656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Last Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>945e88ad-81ab-44b1-93fc-c6d45bca369b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>e05bbd38-54fa-41a0-8337-618248fd7dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-6</value>
      <webElementGuid>338c5dd3-7b4c-4d1f-b052-9f011ed70490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-6</value>
      <webElementGuid>b9af3bc5-6fd7-4947-a7f6-11468dad51df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>620a6af3-aaea-44ec-a7ff-f83a0dda177a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>a1498abe-1d25-4d36-9b9c-9eab9e1fbdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9103070b-2b0a-4bf8-bee8-b63471c27780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-6&quot;)</value>
      <webElementGuid>176e89c5-46f0-4aae-b53f-2f53c118f12f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-6']</value>
      <webElementGuid>ca09dc94-c9eb-41b4-8faf-8bb4e86e1eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CustomerPortalTemplate']/div/div/div[2]/div/div/div/c-campaign-form/div[2]/div/lightning-card/article/div[2]/slot/div/div[2]/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>cf92194a-8ac0-46ee-9867-9eeb15832c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>60ea5584-c74c-4fb4-9c95-d8250de15d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-6' and @placeholder = 'Last Name' and @type = 'text']</value>
      <webElementGuid>f19d5d84-3a3b-445f-a580-d8fcd3bedd58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
