<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Start Here_absolute top-0 left-0 w-full_efd927</name>
   <tag></tag>
   <elementGuidId>15d612b4-de1d-4f7e-85e9-37f760dbbcf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[text()='Start Here'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.absolute.top-0.left-0.w-full.h-full.rounded-full.transition-opacity.opacity-50.bg-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='site-header-mobile-nav-trigger']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Open navigation&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>83d91d65-aedc-4318-a309-8ba1c7b37985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute top-0 left-0 w-full h-full rounded-full transition-opacity opacity-50 bg-white</value>
      <webElementGuid>edda1509-2ef8-43fc-9986-293ff53fdcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[text()='Start Here'])[1]</value>
      <webElementGuid>d1e113b4-dc9f-490d-8fec-0dae79986b42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='site-header-mobile-nav-trigger']/div</value>
      <webElementGuid>374d5370-d242-4f19-a84b-3b93046faecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/div</value>
      <webElementGuid>237382bb-be07-4b9a-8aee-1a47f602f011</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
