<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type in the characters you see in the_e8c10c</name>
   <tag></tag>
   <elementGuidId>6fdaec0b-b4b3-48a6-b1b7-e14f1417a332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mailpoet_submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Get XPath cheat sheet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Get XPath cheat sheet&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30f8f4f0-17df-47dd-9e68-0e2cf0e8f891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>02d687b1-f853-4d74-ae4a-1589debd16be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mailpoet_submit</value>
      <webElementGuid>c2aa4c25-02ef-4cd3-a45b-ef48051e7a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Get XPath cheat sheet</value>
      <webElementGuid>eb1e4912-3602-4b8c-81b2-8e52ae6e7028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>subscribe-submit-button</value>
      <webElementGuid>bb574d0a-e6c8-42fa-8d2b-2d55698dede5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mailpoet_captcha_form&quot;)/div[@class=&quot;mailpoet_form_hide_on_success&quot;]/div[@class=&quot;mailpoet_paragraph&quot;]/input[@class=&quot;mailpoet_submit&quot;]</value>
      <webElementGuid>18309bbc-1570-471c-aae3-66d2adb031f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Get XPath cheat sheet']</value>
      <webElementGuid>90dc8051-2ad4-4cfb-9e30-e4e50dfb6168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mailpoet_captcha_form']/div/div[2]/input</value>
      <webElementGuid>2ff89e54-a8da-4173-a8c9-4b1b277c1ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>d2d07374-ea5e-4ff9-9daf-ca0a23ae1baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>8df1e765-478c-43f8-a540-4872c9e26529</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
