<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Resources</name>
   <tag></tag>
   <elementGuidId>9cfe6fd5-fe0d-49c5-a391-905c7e09dfa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#site-header-nav-resources-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='site-header-nav-resources-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Resources&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>13c296f3-8598-4a70-9e3f-d4a0d8a86db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2 px-7 rounded-full uppercase tracking-[.14em] outline-none</value>
      <webElementGuid>78a75e05-e784-4f09-916b-8d0cd57f8e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>site-header-nav-resources-3</value>
      <webElementGuid>00f73a60-a801-4ba0-920f-0ea1d94c3224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resources</value>
      <webElementGuid>1ef0db19-3f74-46e4-822e-ef3f9d2b9288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header-nav-resources-3&quot;)</value>
      <webElementGuid>2f1e103d-67a2-4cfa-88f4-51e9d9d766c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='site-header-nav-resources-3']</value>
      <webElementGuid>e8dbfb99-57dd-4db5-b9be-0614ab80aaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/nav/div/div/div[2]/div/ul/li[4]/button</value>
      <webElementGuid>31df7644-2623-49ea-a384-8cfe23200fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/following::button[1]</value>
      <webElementGuid>f2499a72-602b-45a2-8702-2e73ec66947e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Hired'])[1]/following::button[2]</value>
      <webElementGuid>e27d8fe7-cd6f-4aef-82f2-14b2aa1312ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GenAI'])[1]/preceding::button[1]</value>
      <webElementGuid>c9f15e82-f52b-401f-a160-33adecdc2c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Talent'])[1]/preceding::button[1]</value>
      <webElementGuid>c42a59d7-c9d9-4d7a-910b-fee8cb345be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resources']/parent::*</value>
      <webElementGuid>798ecf59-408e-4e69-880a-959f8d198747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button</value>
      <webElementGuid>9735d6ad-b54c-42a2-8560-37fa83978ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'site-header-nav-resources-3' and (text() = 'Resources' or . = 'Resources')]</value>
      <webElementGuid>1961ebd7-9943-469a-ac19-a853cd070bdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
