<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Services</name>
   <tag></tag>
   <elementGuidId>2a60a287-e078-475d-9512-b0d83443ca09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#site-header-nav-services-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='site-header-nav-services-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Services&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e796d2a-0b9e-4b32-a8f1-7f63ad00024b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-2 px-7 rounded-full uppercase tracking-[.14em] outline-none</value>
      <webElementGuid>47b707cb-6ad7-4e37-b26d-9ad2548e333b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>site-header-nav-services-0</value>
      <webElementGuid>605148b1-2dfe-4bae-a0a5-ab40511985b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Services</value>
      <webElementGuid>e961bd47-5d4f-4bb3-af00-906e7a95da44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-header-nav-services-0&quot;)</value>
      <webElementGuid>164a0758-f973-4f8a-b3d9-1f2896f21cf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='site-header-nav-services-0']</value>
      <webElementGuid>6bf65021-2054-47d8-9c04-b250dcbde839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/nav/div/div/div[2]/div/ul/li/button</value>
      <webElementGuid>c6fe7f26-8b92-4a66-ae17-3ae540e85fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get Hired'])[1]/preceding::button[1]</value>
      <webElementGuid>397bcbe1-09b1-4d2c-b38f-cc644e3ac2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::button[2]</value>
      <webElementGuid>d018877a-0787-4440-a88b-6c39c1852618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Services']/parent::*</value>
      <webElementGuid>c79f3e90-2b3f-463f-9f16-5080fc6d8e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2b4eb901-aa90-4418-a3c4-a0e26dff3e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'site-header-nav-services-0' and (text() = 'Services' or . = 'Services')]</value>
      <webElementGuid>8b465cfd-ffd1-4b35-9bb0-1f96adce1c0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
