<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Content</name>
   <tag></tag>
   <elementGuidId>7f872037-8b87-4b22-97da-8b5a608ae6de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[text()='Contact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[text()='Contact']</value>
      <webElementGuid>f2749cba-1919-488a-8377-6b749a6def44</webElementGuid>
   </webElementProperties>
</WebElementEntity>
