<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Flights_chNavIcon appendBottom2 chSpri_ac3d96</name>
   <tag></tag>
   <elementGuidId>0e1d9baf-12f0-460a-b0ed-cd6e6151def6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.chNavIcon.appendBottom2.chSprite.chHotels</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SW']/div/div[2]/div/div/nav/ul/li[2]/span/a/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hotels&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f38bdd01-66b5-41db-97b0-48d05f7f6699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chNavIcon appendBottom2 chSprite chHotels</value>
      <webElementGuid>3b85610e-a8aa-4282-b7fa-db183e983126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SW&quot;)/div[@class=&quot;landingContainer eng&quot;]/div[@class=&quot;headerOuter&quot;]/div[@class=&quot;chHeaderWrapper navOnly&quot;]/div[@class=&quot;chHeaderContainer&quot;]/nav[1]/ul[@class=&quot;makeFlex font12 headerIconsGap&quot;]/li[@class=&quot;menu_Hotels&quot;]/span[1]/a[@class=&quot;headerIcons makeFlex hrtlCenter column&quot;]/span[@class=&quot;headerIconWrapper&quot;]/span[@class=&quot;chNavIcon appendBottom2 chSprite chHotels&quot;]</value>
      <webElementGuid>bfaa2249-34a3-4231-a89a-c13831b7a10f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SW']/div/div[2]/div/div/nav/ul/li[2]/span/a/span/span</value>
      <webElementGuid>4e2cb1e1-bc31-4007-8287-ef1192d98b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span/a/span/span</value>
      <webElementGuid>0815ec55-e633-417e-bd8d-993002ee9d77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
