<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Salesforce</name>
   <tag></tag>
   <elementGuidId>a9a6df81-8104-4bda-a659-ab55b12a6697</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/footer/div/div/div/div/div[2]/ul/li/a/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Salesforce&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c326844-7500-43c7-8b46-d756534eced0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salesforce</value>
      <webElementGuid>0cabb296-c685-4cde-b8cd-40b6ca34ed8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/footer[@class=&quot;bg-white p-[var(--currentInset)]&quot;]/div[@class=&quot;bg-darkNavy text-[rgba(255,255,255,0.6)] text-center lg:text-left rounded-[var(--currentRadius)] pt-14 lg:py-20 pb-28 flex flex-col items-center&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;flex flex-col items-center lg:flex-row lg:items-start lg:w-full lg:justify-between lg:pb-14&quot;]/div[@class=&quot;py-14 lg:py-0 lg:flex lg:items-start lg:grid lg:grid-flow-col lg:grid-cols-3&quot;]/div[@class=&quot;mt-9 lg:px-10 first:mt-0 lg:mt-0 lg:w-[180px] xl:w-[210px] max-w-[234px]&quot;]/ul[1]/li[1]/a[@class=&quot;text-[17px] block py-1&quot;]/span[1]/span[@class=&quot;relative inline bg-clip-text&quot;]/span[1]</value>
      <webElementGuid>3cb8a875-f388-4e69-9e9c-56b39f8a70e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/footer/div/div/div/div/div[2]/ul/li/a/span/span/span</value>
      <webElementGuid>778f4b70-4757-485d-9aa3-1bf158cf06d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partner'])[1]/following::span[3]</value>
      <webElementGuid>04a50f10-e36e-4349-b03c-0e21d86d0990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Job Seekers'])[1]/following::span[3]</value>
      <webElementGuid>f0355665-263d-4611-8fe8-be6a7b7103c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pega'])[1]/preceding::span[1]</value>
      <webElementGuid>b60bd251-5f38-4e8e-a740-bcb176a5d11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appian'])[1]/preceding::span[4]</value>
      <webElementGuid>8ba647b0-d02b-4e76-b0c5-e3f1d13011c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Salesforce']/parent::*</value>
      <webElementGuid>0b72524e-9f02-43a7-882b-d6017e1819c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a/span/span/span</value>
      <webElementGuid>90405132-095b-49e6-93c0-474741f5493b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Salesforce' or . = 'Salesforce')]</value>
      <webElementGuid>1db79a52-f2da-4ca4-bac8-3813e58201df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
