<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Awards</name>
   <tag></tag>
   <elementGuidId>70a6e7db-b1c0-44fb-ab52-c118357e2676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/section/div/div/div/div/div/div[2]/a[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Awards&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3bec9a72-44dc-4c1e-8be6-14b5e1a59bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative top-[-1px]</value>
      <webElementGuid>4b1a9558-c36b-40d5-8fda-576ab6acce67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Awards</value>
      <webElementGuid>dce84381-ae0a-48e0-baf3-2b771ce610c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/main[1]/section[@class=&quot;bg-white pt-[16vh] lg:pt-[min(25vh,350px)] pb-[16vh] lg:pb-[min(25vh,350px)]&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;mt-12 lg:mt-[72px] mb-16&quot;]/div[1]/div[@class=&quot;overflow-auto no-scrollbar flex scroll-x-contain ml-[-24px]&quot;]/div[@class=&quot;min-w-[calc(100%+18px)] flex&quot;]/div[@class=&quot;gap-x-3 flex justify-start gap-x-3&quot;]/a[@class=&quot;font-bold uppercase text-sm lg:text-base leading-none px-4 py-2 mt-3 rounded-full whitespace-nowrap text-navy bg-lightGray&quot;]/span[@class=&quot;relative top-[-1px]&quot;]</value>
      <webElementGuid>88cb701f-2e0a-4342-aa51-65ddbf34b77e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div/div/div/div/div/div[2]/a[4]/span</value>
      <webElementGuid>3dc5c034-37d8-4364-a7c3-7193d45ea132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Article'])[1]/following::span[1]</value>
      <webElementGuid>84e94d94-c7e9-490d-bfc1-7aa754255fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumni Stories'])[1]/following::span[2]</value>
      <webElementGuid>abf9596b-9a0e-41bc-a8d9-73e8404ce65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog Post'])[1]/preceding::span[1]</value>
      <webElementGuid>c7783e2c-b6ec-4d1f-b8ea-24334992b6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Stories'])[1]/preceding::span[2]</value>
      <webElementGuid>9048f17c-1ffd-44c5-9631-9937147a40c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Awards']/parent::*</value>
      <webElementGuid>10564121-0f27-4f7d-a3d9-a22013bd2734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/span</value>
      <webElementGuid>cfa4e461-f758-4742-8901-2a5e7385061f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Awards' or . = 'Awards')]</value>
      <webElementGuid>f82ad009-b16c-4588-bfa0-dedea27a3443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
