<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Article</name>
   <tag></tag>
   <elementGuidId>03e41b61-61cf-425b-b95d-9bdc8a942528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/section/div/div/div/div/div/div[2]/a[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Article&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ddcd50cc-48e3-4f3c-ac23-25a9289a9aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative top-[-1px]</value>
      <webElementGuid>2581ebef-d5a8-4443-ab9f-5da2da5b08b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Article</value>
      <webElementGuid>5b2d1b5e-afa5-401a-bdc8-47eeced38607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/main[1]/section[@class=&quot;bg-white pt-[16vh] lg:pt-[min(25vh,350px)] pb-[16vh] lg:pb-[min(25vh,350px)]&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;mt-12 lg:mt-[72px] mb-16&quot;]/div[1]/div[@class=&quot;overflow-auto no-scrollbar flex scroll-x-contain ml-[-24px]&quot;]/div[@class=&quot;min-w-[calc(100%+18px)] flex&quot;]/div[@class=&quot;gap-x-3 flex justify-start gap-x-3&quot;]/a[@class=&quot;font-bold uppercase text-sm lg:text-base leading-none px-4 py-2 mt-3 rounded-full whitespace-nowrap text-navy bg-lightGray&quot;]/span[@class=&quot;relative top-[-1px]&quot;]</value>
      <webElementGuid>7ef9b5da-b044-4fb5-8049-ebb83c9b49c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/section/div/div/div/div/div/div[2]/a[3]/span</value>
      <webElementGuid>c846c617-9e83-48c0-ae00-aa75d30c7b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alumni Stories'])[1]/following::span[1]</value>
      <webElementGuid>26897e27-4182-437a-b801-0cd621f662ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::span[2]</value>
      <webElementGuid>d2119c11-8d71-4667-b86d-57916c092d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Awards'])[1]/preceding::span[1]</value>
      <webElementGuid>a50e9720-de22-41f1-a25a-0370d4bb1249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog Post'])[1]/preceding::span[2]</value>
      <webElementGuid>e366d9fc-3c49-4447-b069-aff3fa0ab199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Article']/parent::*</value>
      <webElementGuid>46a751e1-efa7-4ab3-ba23-395e8386f015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span</value>
      <webElementGuid>bc109231-695d-4350-bbfe-18738d3f9000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Article' or . = 'Article')]</value>
      <webElementGuid>6d5c0e88-046b-46bd-b774-8bd9306aebe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
