<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Information_email</name>
   <tag></tag>
   <elementGuidId>e71f6fc8-bd89-4774-84f3-2099eae96ed9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Email Address&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbac3deb-c960-416e-ae71-174664dbfa6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>18513443-9411-45b7-941c-78031081559c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-2 rounded-lg px-[16px] pt-[17px] pb-[19px]  leading-none focus:border-blue transition-all duration-300 shadow-[0px_0px_0px_0px_rgba(7,65,203,0.15)] focus:shadow-[0px_0px_0px_4px_rgba(7,65,203,0.15)] outline-none</value>
      <webElementGuid>576d4809-237f-4204-978a-e6b7533af803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>325e3120-dbda-430a-a5e3-3bd56c3dddb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>45e7c9e8-55f4-43d9-be58-b1ef37e06b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>c</value>
      <webElementGuid>bdb3a195-4363-479c-a989-956451f6e17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apply&quot;)/form[2]/fieldset[@class=&quot;flex flex-col mb-6 last:mb-0 min-w-0&quot;]/div[2]/div[@class=&quot;grid md:grid-cols-2 gap-2 md:gap-5&quot;]/div[@class=&quot;flex flex-col relative&quot;]/input[@class=&quot;border-2 rounded-lg px-[16px] pt-[17px] pb-[19px]  leading-none focus:border-blue transition-all duration-300 shadow-[0px_0px_0px_0px_rgba(7,65,203,0.15)] focus:shadow-[0px_0px_0px_4px_rgba(7,65,203,0.15)] outline-none&quot;]</value>
      <webElementGuid>67ecede6-745e-47da-ba01-d04356533cd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>9e01be29-46f3-48f7-a003-c14531efe4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apply']/form[2]/fieldset[2]/div[2]/div/div/input</value>
      <webElementGuid>fc9c2594-ed94-4602-89ef-ef7d7c6b442c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div[2]/div/div/input</value>
      <webElementGuid>5a52195c-d661-43dd-90c8-1f18a1bc5213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @type = 'email' and @placeholder = 'Email Address']</value>
      <webElementGuid>59cc4c6d-1b99-4415-b05b-d0fd123d7bd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
