<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full Name_lastName</name>
   <tag></tag>
   <elementGuidId>8b411b0b-db45-464d-821c-4748e69948fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;lastName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='lastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Last Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9750de59-9ee8-4bf5-ab19-83867c0bdefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>6ea4a0dc-2a60-41eb-9b47-2c4772fc34e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-2 rounded-lg px-[16px] pt-[17px] pb-[19px]  leading-none focus:border-blue transition-all duration-300 shadow-[0px_0px_0px_0px_rgba(7,65,203,0.15)] focus:shadow-[0px_0px_0px_4px_rgba(7,65,203,0.15)] outline-none</value>
      <webElementGuid>e3d33642-fa5f-4e09-9dc1-23dbc154263f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87984ef3-0576-4883-9730-282fe7dfeec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>8cf51aca-7df2-495a-8e59-48d3b40e84da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apply&quot;)/form[2]/fieldset[@class=&quot;flex flex-col mb-6 last:mb-0 min-w-0&quot;]/div[2]/div[@class=&quot;grid grid-cols-2 gap-2 md:gap-5&quot;]/div[@class=&quot;flex flex-col relative&quot;]/input[@class=&quot;border-2 rounded-lg px-[16px] pt-[17px] pb-[19px]  leading-none focus:border-blue transition-all duration-300 shadow-[0px_0px_0px_0px_rgba(7,65,203,0.15)] focus:shadow-[0px_0px_0px_4px_rgba(7,65,203,0.15)] outline-none&quot;]</value>
      <webElementGuid>dfc16b8a-b36c-4c88-b2b0-3e5fe9af1c7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='lastName']</value>
      <webElementGuid>13425c07-cd70-40a5-9345-c76a8bb55a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apply']/form[2]/fieldset/div[2]/div/div[2]/input</value>
      <webElementGuid>a921c023-b1a1-4ccf-afcb-5ac14bb99f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>eb74acf1-0f94-4da2-931b-786dee79490d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'lastName' and @type = 'text' and @placeholder = 'Last Name']</value>
      <webElementGuid>63a1bfd9-632c-4e0b-82ed-60d714c9a049</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
