<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Party_img-responsive</name>
   <tag></tag>
   <elementGuidId>7df17aa5-cf1a-4f7a-92da-45d12388cc83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='2447910730']/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-responsive</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Party Niaboytown ₹4003 Duration 6 Hours&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8b8e3407-dfdb-420b-a6f7-955878cb83b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive</value>
      <webElementGuid>9826154e-bff8-4b78-904a-64e3c3350bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.pexels.com/photos/837745/pexels-photo-837745.jpeg?auto=compress&amp;cs=tinysrgb&amp;h=650&amp;w=940</value>
      <webElementGuid>af519b79-5c92-4551-9987-ad998b1d59ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2447910730&quot;)/div[@class=&quot;activity-card&quot;]/img[@class=&quot;img-responsive&quot;]</value>
      <webElementGuid>ed8f50bc-a86d-4c1e-b796-c36ac1efe06e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='2447910730']/div[2]/img</value>
      <webElementGuid>5b94157a-8b40-4627-9194-c818cd8347e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://images.pexels.com/photos/837745/pexels-photo-837745.jpeg?auto=compress&amp;cs=tinysrgb&amp;h=650&amp;w=940')]</value>
      <webElementGuid>84397d9b-3971-429f-8e19-620bcc61239c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>65982c5c-cfca-4ad5-8017-2cf9b64058e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://images.pexels.com/photos/837745/pexels-photo-837745.jpeg?auto=compress&amp;cs=tinysrgb&amp;h=650&amp;w=940']</value>
      <webElementGuid>a607b77b-dc1c-4db1-a577-5c914b1c9fc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
