<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Trains  Trains</name>
   <tag></tag>
   <elementGuidId>69f54429-5310-44d9-b5df-337501abecaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.menu_Trains > span > a.headerIcons.makeFlex.hrtlCenter.column</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SW']/div/div[2]/div/div/nav/ul/li[5]/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Trains&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b6223de-1e96-4ae1-9840-f4b7230f3638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.makemytrip.com/railways/</value>
      <webElementGuid>42111f51-08d5-4417-858a-5813f9d9d99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>headerIcons makeFlex hrtlCenter column</value>
      <webElementGuid>ae6cbe2a-a413-4ece-b7cd-52b65879fdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Trains  Trains </value>
      <webElementGuid>3edb9882-225e-4f56-9a88-8db804983114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SW&quot;)/div[@class=&quot;landingContainer eng&quot;]/div[@class=&quot;headerOuter&quot;]/div[@class=&quot;chHeaderWrapper navOnly&quot;]/div[@class=&quot;chHeaderContainer&quot;]/nav[1]/ul[@class=&quot;makeFlex font12 headerIconsGap&quot;]/li[@class=&quot;menu_Trains&quot;]/span[1]/a[@class=&quot;headerIcons makeFlex hrtlCenter column&quot;]</value>
      <webElementGuid>d76a8a48-fa17-49a7-88be-87bcacf81f8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SW']/div/div[2]/div/div/nav/ul/li[5]/span/a</value>
      <webElementGuid>193e43cb-2beb-460a-94e3-efed63c05f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.makemytrip.com/railways/')]</value>
      <webElementGuid>7afd4e04-ef28-4946-b6ff-8ee093abee77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/span/a</value>
      <webElementGuid>490ff1b7-3b09-40f0-913c-28ced2eb0b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.makemytrip.com/railways/' and (text() = ' Trains  Trains ' or . = ' Trains  Trains ')]</value>
      <webElementGuid>967b491f-a14e-42a5-a5f8-b9d3d2768a9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
