<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Proceed to buy</name>
   <tag></tag>
   <elementGuidId>ba4c8b8f-d2ea-4f77-9fe2-bd5d98f0d87d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Proceed to buy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>af9af930-8e88-4a9f-8e02-df7b9576caf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ed0c339-2926-4f27-b6cf-eb822666013b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button !rounded-full !px-12 !h-[50px] !w-full css-1ai4qkv</value>
      <webElementGuid>4643fa1e-6077-4e4f-9491-b44364e54233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed to buy</value>
      <webElementGuid>fbce2ec8-36fb-4960-a71f-8e521c940e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex flex-col w-full h-screen&quot;]/main[@class=&quot;flex-auto mt-[90px] px-6 md:px-0 md:mx-auto container&quot;]/div[@class=&quot;h-full&quot;]/div[@class=&quot;flex lg:flex-row flex-col h-full pb-20&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;w-full lg:w-[450px] p-8 bg-white rounded-[10px] shadow border border-zinc-100 flex-col justify-start items-start&quot;]/div[@class=&quot;flex-col gap-4 flex w-full&quot;]/div[@class=&quot;text-center w-full mt-4&quot;]/button[@class=&quot;chakra-button !rounded-full !px-12 !h-[50px] !w-full css-1ai4qkv&quot;]</value>
      <webElementGuid>fa0a61f1-5793-4ab3-b7ea-5cf57d22bdca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>d54e339f-4503-4b6b-9207-24f215c73e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/div/div/div[2]/div/div[2]/div[4]/button</value>
      <webElementGuid>a0032d65-c62d-4ea2-bbb0-099e8b5974da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::button[1]</value>
      <webElementGuid>944e5afc-e98b-45f7-869e-18ee4dae1f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/preceding::button[1]</value>
      <webElementGuid>6a127bbd-22a3-4b42-884f-67e0314858a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proceed to buy']/parent::*</value>
      <webElementGuid>0e9c6290-c397-47e7-859e-16f9adacee44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>bba713d2-f279-465f-bb2f-0937865324d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Proceed to buy' or . = 'Proceed to buy')]</value>
      <webElementGuid>30c78b69-b909-4bbc-bf85-8bdf31b013dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
