<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CreditDebit Card_cvv</name>
   <tag></tag>
   <elementGuidId>f9f7336e-fd29-43ea-868f-9d86263726b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-20</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-20']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;CVV&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc946a2a-7e71-415e-8c30-d1b592cdb79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cvv</value>
      <webElementGuid>8f36b281-fb3f-4a37-b156-fd6d06ab9435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CVV</value>
      <webElementGuid>9a3c5578-5a65-4eda-a8da-728b6c138ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-20</value>
      <webElementGuid>2d338fd2-d3e2-4fc7-9e7f-7f6f4498ab50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-19xymc2</value>
      <webElementGuid>c70e4cd3-6988-4fd8-b53c-d61adae59ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-20&quot;)</value>
      <webElementGuid>e251d4f2-578a-4626-881d-eb1344339c08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-20']</value>
      <webElementGuid>d0f41289-ba4c-4cde-b256-3d8394c0d119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion-panel-22']/form/div[2]/div[2]/div/input</value>
      <webElementGuid>6f681b45-8721-49b0-ac8a-1c5506b155bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/form/div[2]/div[2]/div/input</value>
      <webElementGuid>a1f043d5-e950-4708-8f67-ac09ebf18423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cvv' and @placeholder = 'CVV' and @id = 'field-20']</value>
      <webElementGuid>70c2a502-dcb8-412c-88bc-9e2cc0cc27b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
