<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CreditDebit Card_cardNumber</name>
   <tag></tag>
   <elementGuidId>7d471ecc-28f1-48cb-9538-7dc0dd1df1bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Card Number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df247bd3-a7c3-4f07-9f77-9df5a40c2554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardNumber</value>
      <webElementGuid>5e8646fc-68bd-4ab6-85d7-5b47635d6348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Card Number</value>
      <webElementGuid>1dcc0d1f-9ede-4585-8247-4d54b88ce7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-18</value>
      <webElementGuid>7a14cee9-c974-41f3-8b46-50e60a5061c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-19xymc2</value>
      <webElementGuid>e6fa9e94-f4eb-4a99-97a4-6a5914324588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-18&quot;)</value>
      <webElementGuid>ade5e888-5a26-4866-b164-9f7f6ce3f440</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-18']</value>
      <webElementGuid>d1b2dc68-25cb-4b25-9385-f1822c09c256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion-panel-22']/form/div/input</value>
      <webElementGuid>47e33cff-97b2-4390-9c9d-14bf0d4391fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/form/div/input</value>
      <webElementGuid>b64eec88-ae5d-4595-8cf1-708550e1e42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cardNumber' and @placeholder = 'Card Number' and @id = 'field-18']</value>
      <webElementGuid>bdceec6d-f79a-4144-8f21-b6f8d35629b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
