<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CreditDebit Card_cardHolderName</name>
   <tag></tag>
   <elementGuidId>69c6f310-c2da-47f3-8f03-0d093efa8d16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-21']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Card Holder Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>faa4a3be-22d2-4de2-807b-3b299c820255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardHolderName</value>
      <webElementGuid>c661be6f-a6a5-4a3b-8922-43a5b860fb96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Card Holder Name</value>
      <webElementGuid>8c837d15-c71a-4527-8195-66b373ac44bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-21</value>
      <webElementGuid>80b11535-6c85-413b-b5a5-6657b667be47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-19xymc2</value>
      <webElementGuid>4f9600c6-99e5-44da-9dcd-5f0424beec36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-21&quot;)</value>
      <webElementGuid>15fb723c-8ee8-4315-8d20-9a89a89a27ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-21']</value>
      <webElementGuid>abc933f0-1d54-49ea-a4d3-52e25ab81a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion-panel-22']/form/div[3]/input</value>
      <webElementGuid>92e49d09-3800-4b95-a8eb-4532aaf38aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>1c47439e-8f75-435b-b77c-eed443d0d65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cardHolderName' and @placeholder = 'Card Holder Name' and @id = 'field-21']</value>
      <webElementGuid>82b9ca3f-7366-4074-819d-ff5e29a13de8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
