<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-6</name>
   <tag></tag>
   <elementGuidId>7aeccd85-036f-4b20-8be3-428f610124ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Last Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>013f7dcb-2333-4665-8311-8ee8156917c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>e4f46796-ed79-48b1-97d2-00e1a59d2656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-6</value>
      <webElementGuid>34dd5d6a-e61b-4b8d-92c1-3d0adcff5f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-6</value>
      <webElementGuid>6bae2752-26d8-4ad9-ad97-c64c4874da98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89b916fe-00e6-4b7a-b60e-27354a5fe5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>cd4d4e96-9932-46fe-8adb-04ed4e951c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>169940a6-64bb-41a8-b33d-5095d8309ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-6&quot;)</value>
      <webElementGuid>8b9162f4-74a0-48f6-a25e-d9f381d36bcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-6']</value>
      <webElementGuid>17f0472a-b0bf-4032-bb8a-ef4ebe5b228b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CustomerPortalTemplate']/div/div/div[2]/div/div/div/c-campaign-form/div[2]/div/lightning-card/article/div[2]/slot/div/div[2]/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>c4b2eb8b-f85c-44df-b318-01f3a6e1af81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>86b51b12-de5e-4979-b4dc-d17d0bc54db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-6' and @placeholder = 'Last Name' and @type = 'text']</value>
      <webElementGuid>4764ac7f-fad8-44dc-844c-e22576edbf65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
