<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-4</name>
   <tag></tag>
   <elementGuidId>1b4b96a2-f1f9-484e-af89-14eda714e590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;First Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c4f9f96-d929-4ac2-9d47-808cd3f7b4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>f2e93520-281a-4bb1-a2b9-0d93bfda0ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-errormessage</name>
      <type>Main</type>
      <value>help-message-4</value>
      <webElementGuid>cd6fb00a-7120-494b-a332-74089a444011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-4</value>
      <webElementGuid>ce99d0f4-aceb-4da7-af33-99000e889f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92878983-adec-4b69-9fe5-53351a99c127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>58dc8fb8-8565-45c1-9cba-195ba5f0a0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>747cfd06-1907-4eaa-8ede-3605eeb1831e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-4&quot;)</value>
      <webElementGuid>43f0c99f-13fa-4d12-a175-97f51cd0a16a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-4']</value>
      <webElementGuid>5b87c0f0-fa33-4e31-9d9d-95ad86e3377c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CustomerPortalTemplate']/div/div/div[2]/div/div/div/c-campaign-form/div[2]/div/lightning-card/article/div[2]/slot/div/div/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>904d33e6-3b11-41d9-a1fc-bb6c819d7ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a836fac4-acf8-4e71-9fc3-07b79fdb69c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-4' and @placeholder = 'First Name' and @type = 'text']</value>
      <webElementGuid>aa1e4414-74de-464b-b1c1-e6625db9610e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
