<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dataform_field_OTlkMTBlNjFjOGUwX2Zpc_1b3eda</name>
   <tag></tag>
   <elementGuidId>337805a2-328c-4ec1-93d9-a65f4f022c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_first_name_7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form_first_name_7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Name *&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d700472c-ed92-4134-8686-16208244e8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c8cf777-31c4-41db-8b8a-d20552781aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>given-name</value>
      <webElementGuid>1d62c7bb-23f6-495c-aebf-5b3c42b1b3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mailpoet_text</value>
      <webElementGuid>690a6926-30d8-4dfe-8af5-39a2d251b684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_first_name_7</value>
      <webElementGuid>81717394-76f6-4a46-bb8a-1433b0e31231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[form_field_OTlkMTBlNjFjOGUwX2ZpcnN0X25hbWU=]</value>
      <webElementGuid>69ea4fe5-5578-4e2c-b3eb-16a90077024e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>fadbf8e3-5e14-4658-89fc-0a559ff2e35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>form_first_name</value>
      <webElementGuid>f13594f9-dcf2-44cf-aad5-1c340eb86d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name *</value>
      <webElementGuid>2e6fff02-2dcc-442a-a7c2-845837039ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-names</name>
      <type>Main</type>
      <value>[&quot;Please specify a valid name.&quot;,&quot;Addresses in names are not permitted, please add your name instead.&quot;]</value>
      <webElementGuid>ac5688c2-8358-4285-9d6e-755f38f5eab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c0a51229-a286-4603-bd9b-c875906b1516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-errors-container</name>
      <type>Main</type>
      <value>.mailpoet_error_first_name_</value>
      <webElementGuid>169f6b3c-ffd9-45ba-8295-fdffe5e894e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>95e52215-e392-42c1-a203-e649337eab03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_first_name_7&quot;)</value>
      <webElementGuid>0fe751de-e5fb-4888-aa34-0c0480205fbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_first_name_7']</value>
      <webElementGuid>a0e9a85b-b7f6-4fd8-8529-ec57f95287ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mp_form_below_posts7']/form/div[2]/div/div/div/input</value>
      <webElementGuid>c159e83a-28f8-40ce-b99c-2475be0e2913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>c835dea5-56e1-43c7-9336-c23be34c3372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'form_first_name_7' and @name = 'data[form_field_OTlkMTBlNjFjOGUwX2ZpcnN0X25hbWU=]' and @title = 'Name' and @placeholder = 'Name *']</value>
      <webElementGuid>4aa1e3be-e6a3-4b11-834c-450666489490</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
