<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dataform_field_ODhhN2IwZjQ3NTMzX2VtYWls</name>
   <tag></tag>
   <elementGuidId>6155230a-a3ac-4883-bc67-dc4271fe799b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form_email_7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form_email_7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Email Address *&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d332d68f-71dc-4a5a-b06c-f32ea14e201a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>bd94abab-acd4-4d79-a561-f2275b93236f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>1f60e0bc-956a-4ede-aee9-98608a17bc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mailpoet_text</value>
      <webElementGuid>ce225d30-6f63-40fb-98be-1d9c60a9de75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_email_7</value>
      <webElementGuid>3dcef958-c1c1-4171-8d94-4fbcafd58b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[form_field_ODhhN2IwZjQ3NTMzX2VtYWls]</value>
      <webElementGuid>8e13fc2e-eb42-4d51-9c5d-fd676c8456b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>f6bd76fc-dac2-4865-a68f-7ef660775b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>form_email</value>
      <webElementGuid>6d8c06b8-7628-4d20-b451-03af28b56a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email Address *</value>
      <webElementGuid>8e81b5f3-10fd-46c9-9caf-82a7504dd4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>30d0ac6f-3e4e-4a5d-a91e-0ee57e2ba9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-minlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>5829813e-a014-48a9-8977-f25233607ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>7f4970a8-4d81-4a9f-a7ad-144d32f30f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-type-message</name>
      <type>Main</type>
      <value>This value should be a valid email.</value>
      <webElementGuid>dede1948-448f-456e-b9aa-73cc884c0620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-errors-container</name>
      <type>Main</type>
      <value>.mailpoet_error_email_</value>
      <webElementGuid>ce144b18-b382-4840-9794-012695ebc072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>bd0bddc8-b24c-4ff7-8f16-7654ac73db40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_email_7&quot;)</value>
      <webElementGuid>3a5c5d9a-5fc0-4d44-96c4-32d3efbe851b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_email_7']</value>
      <webElementGuid>2d900031-b9b3-449b-8356-2dce532434f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mp_form_below_posts7']/form/div[2]/div/div[2]/div/input</value>
      <webElementGuid>22ca8d82-425e-4828-83e8-26445a965dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a0d5b8da-18c1-47b0-949f-630d1555aac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'form_email_7' and @name = 'data[form_field_ODhhN2IwZjQ3NTMzX2VtYWls]' and @title = 'Email Address' and @placeholder = 'Email Address *']</value>
      <webElementGuid>832d6058-9a1a-4577-8de5-62cb3c6133b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
