<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dataform_field_OTlkMTBlNjFjOGUwX2Zpc_1b3eda</name>
   <tag></tag>
   <elementGuidId>337805a2-328c-4ec1-93d9-a65f4f022c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form_first_name_7']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='form_first_name_7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form_first_name_7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Name *&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c764ea0f-3669-46a1-9fc1-63204124a325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>499db64d-20e7-44e1-a6f5-4df6be18e0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>given-name</value>
      <webElementGuid>67ee9889-616c-45be-9c8c-989c524d343f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mailpoet_text</value>
      <webElementGuid>55340e36-d7f8-4746-b8d6-b0c997e08870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_first_name_7</value>
      <webElementGuid>e265abd2-e06c-4835-9c73-17964deae86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[form_field_OTlkMTBlNjFjOGUwX2ZpcnN0X25hbWU=]</value>
      <webElementGuid>cdd0e2a7-5c9c-4576-9b7c-7930c5fbedf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>63957271-3f28-497c-bee8-add2aef46b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>form_first_name</value>
      <webElementGuid>2fe142ad-b2a6-4887-a5b0-b91ef679d180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name *</value>
      <webElementGuid>f79e5714-fda1-4bc2-a294-ad80f4671896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-names</name>
      <type>Main</type>
      <value>[&quot;Please specify a valid name.&quot;,&quot;Addresses in names are not permitted, please add your name instead.&quot;]</value>
      <webElementGuid>c87db2e0-700e-454e-a274-0cd34a8aacf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>324e1d73-8332-4b07-ad1c-2c57bc738a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-errors-container</name>
      <type>Main</type>
      <value>.mailpoet_error_first_name_</value>
      <webElementGuid>028da068-1da9-4f9e-9656-0e0d86c8742e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parsley-required-message</name>
      <type>Main</type>
      <value>This field is required.</value>
      <webElementGuid>2739874a-56bc-437b-9b44-a70ebf1fc465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='form_first_name_7']</value>
      <webElementGuid>2ddf01f8-88e3-484a-b201-a86d76a1b851</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_first_name_7']</value>
      <webElementGuid>d2469270-18aa-49fc-8213-fa4376f09b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mp_form_below_posts7']/form/div[2]/div/div/div/input</value>
      <webElementGuid>4e0e2bab-1757-48ee-83e3-6d236bdae434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>a56f7bc1-94d8-4b01-9de5-68049c78092e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'form_first_name_7' and @name = 'data[form_field_OTlkMTBlNjFjOGUwX2ZpcnN0X25hbWU=]' and @title = 'Name' and @placeholder = 'Name *']</value>
      <webElementGuid>789b53bd-0dd3-4070-b7e5-dd61a7cb667e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
